name: Deploy to Home Infrastructure via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Tailscale in Docker
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" --hostname="github-actions-runner"
          tailscale status
          ip a

      # Step 4: Set up SSH key for SSH authentication
      - name: 🌈 Deploy with ssh...
        uses: sebastianjnuwu/ssh-action-deploy@v4
        with:
          IP: ${{ secrets.HOME_SERVER_TAILSCALE_IP }}
          USER: ${{ secrets.HOME_SERVER_USER }}
          KEY: ${{ secrets.HOME_SERVER_SSH_KEY }}
          FOLDER: "/root/.deploy"
          RUN: "ls -a; pwd"

            #cd /data/compose/3
            #git pull origin main
            #./update_repos.sh ./
            #docker-compose up -d
