name: Deploy to Home Infrastructure via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Tailscale in Docker
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" --hostname="github-actions-runner"
          tailscale status
          ip a
      # Step 4: Deploy to Home Server via SSH with Tailscale IP
      - name: 🌈 Deploy with SSH
        uses: sebastianjnuwu/ssh-action-deploy@v4
        with:
          IP: ${{ secrets.HOME_TAILSCALE_IP }}
          USER: ${{ secrets.HOME_SERVER_USER }}
          KEY: ${{ secrets.HOME_SERVER_SSH_KEY }}
          FOLDER: "/"
          RUN: |
            echo "Starting deployment..."
            
            # Navigate to the target folder
            cd /data/compose/3
            
            # Check if the Git repository already exists, if not, clone it
            if [ ! -d ".git" ]; then
              echo "Git repository not found. Cloning repository..."
              git clone https://github.com/Latitude-OpenDATA-SIO-Saintbe/Docker/
            else
              echo "Git repository found. Pulling the latest changes..."
              git pull origin main
            fi
      
            # Run your update script
            ./update_repos.sh ./
            
            # Restart your containers using docker-compose
            docker-compose up -d
            
            # List directory contents and print working directory for debugging
            ls -a
            pwd

