name: Deploy to Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Deploy to Server
      - name: 🌈 Deploy with SSH
        uses: sebastianjnuwu/ssh-action-deploy@v4
        with:
          IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.SERVER_USER }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          FOLDER: "/"
          RUN: |
            echo "Starting deployment..."
            
            # Check if the Git repository already exists, if not, clone it
            if [ ! -d ".git" ]; then
              echo "Git repository not found. Cloning repository..."
              git clone https://github.com/Latitude-OpenDATA-SIO-Saintbe/Docker/
            else
              echo "Git repository found. Pulling the latest changes..."
              git pull origin main
              ./clone_repos.sh .
            fi
            
            # Run your update script
            ./update_repos.sh .
            
            # Restart your containers using docker-compose
            docker-compose up -d
