name: Deploy to Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Deploy to Server
      - name: 🌈 Deploy with SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "Starting deployment..."
            
            # Check if the Git repository already exists, if not, clone it
            if [ ! -d ".git" ]; then
              echo "Git repository not found. Cloning repository..."
              git clone https://github.com/Latitude-OpenDATA-SIO-Saintbe/Docker/
              cd Docker
              ./clone_repos.sh .
            else
              echo "Git repository found. Pulling the latest changes..."
              cd Docker
              git pull origin main
            fi
            
            # Run your update script
            ./update_repos.sh .
            
            # Restart your containers using docker-compose
            docker-compose up -d
