name: Deploy to Home Infrastructure via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Tailscale in Docker
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" --hostname="github-actions-runner"
          tailscale status
          ip a

      # Step 4: Set up SSH key for SSH authentication
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOME_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Ensure the correct Tailscale IP is passed to ssh-keyscan
          ssh-keyscan -H ${{ secrets.HOME_SERVER_TAILSCALE_IP }} >> ~/.ssh/known_hosts

      # Step 5: Deploy to Home Server via SSH with Tailscale IP
      - name: 🌈 Deploy with SSH
        run: |
          echo "Starting deployment..."
          ssh ${{ secrets.HOME_SERVER_USER }}@${{ secrets.HOME_SERVER_TAILSCALE_IP }} << 'EOF'
            cd /data/compose/3
            git pull origin main
            ./update_repos.sh ./
            docker-compose up -d
            ls -a
            pwd
          EOF
